version: '3.8'

services:
  postgres:
    container_name: user-service-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres-network
    depends_on:
      - postgres

  kong:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: kong-gateway
    environment:
      KONG_DATABASE: 'off'
      KONG_PLUGINS: bundled,auth-check
      KONG_LUA_PACKAGE_PATH: /usr/local/share/lua/5.1/?.lua;;
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./ApiGateway/kong.yml:/etc/kong/kong.yml:ro
    networks:
      - kong-net
      - service-net

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: user-service
    ports:
      - "9010:9010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - postgres-network
      - service-net
      - kong-net
    depends_on:
      postgres:
        condition: service_healthy

  school-service:
    build:
      context: .
      dockerfile: SchoolService/Dockerfile
    container_name: school-service
    ports:
      - "9020:9020"
    networks:
      - service-net
      - kong-net
    depends_on:
      - user-service

networks:
  postgres-network:
    driver: bridge
  kong-net:
    driver: bridge
  service-net:
    driver: bridge

volumes:
  postgres_data: